### ISSUE TITLE
Pre-quoted path segments

### ISSUE THREAD

**Issue by RickyCook** [codeinthehole/purl#22]
Currently, you can't set a pre-quoted path segment. This makes it impossible to set a path with a quoted `/` (because it will be treated as a segment, not part of the path so won't be quoted, and passing `%2F` will return `%252F` because the `%` gets quoted).

I have a branch, with tests, but the rabbit hole goes deeper when you try to do things like:

`URL.add_path_segment(quote=True).add_path_segment(quote=False)`

I don't have time to fix this case right now (simply not using purl becomes easier), so thought I'd just raise the issue so that you're aware of it, and point you at my WIP branch, if you'd like to fix that last case. Tests included, so you can see the issue too:

RickyCook/purl#1

**Comment by codeinthehole** [comment]
Hey - sorry for taking so long to respond.

I've added a PR which I think may fix the issue you are describing. Can you have a look and let me know what you think?
