### ISSUE TITLE
Cannot create URL with '@' symbol in password

### ISSUE THREAD

**Issue by dylanfw** [codeinthehole/purl#35]
It isn't currently possible to create a URL when there is an `@` character in the password.

Using the '@' character directly:
`>>> purl.URL("mysql://foo:b@r@localhost")`
`_URLTuple(host='r', username='foo', password='b', scheme='mysql', port=None, path='', query='', fragment='')`

URL encoding it first:
`>>> purl.URL("mysql://foo:b%40r@localhost")`
`_URLTuple(host='localhost', username='foo', password='b%2540r', scheme='mysql', port=None, path='', query='', fragment='')`

A potential solution would be to split on '@' from the right when extracting credentials from the URL.

**Comment by codeinthehole** [comment]
Fixed in v1.5
